### ISSUE TITLE
tf_tree is strange when I launch lidar_localization_ros2 with odom frame

### ISSUE THREAD

**Issue by atinfinity** [rsasaki0109/lidar_localization_ros2#58]
## Summary

tf_tree is strange when I launch `lidar_localization_ros2` with odom frame. There is no `map` frame in rqt_tf_tree.

![Image](https://github.com/user-attachments/assets/08ef64dc-6228-43b1-90e8-9b8a906b0812)

I published "odom" frame for navigation2.

![Image](https://github.com/user-attachments/assets/0503554c-1af3-4b97-8511-dbffec1d08ca)

And, I used the following configuration.

```yaml
/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 2.0
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 4
      ndt_max_iterations: 35
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 40.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/xxx/maps/map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      use_imu: false
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_footprint
```
